###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "user": "Otto",
    "password": "123"
}

###
GET http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:9000/api/users/62a4e12b38fd04b620d0a514 HTTP/1.1
Content-Type: application/json

{
    "user": "Otto Habsburg",
    "password": "123"
}

###
DELETE http://localhost:9000/api/users/62a4dc366708da835178e44b HTTP/1.1
Content-Type: application/json