// You can test requests with Rest Client in this file
### Add user
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "user": "test",
    "password": "test"
}

### Get users
GET http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

### Search user
GET http://localhost:9000/api/users/test HTTP/1.1
Content-Type: application/json

### Verify user
GET http://localhost:9000/api/users/v/test HTTP/1.1
Content-Type: application/json

### Update user
PUT http://localhost:9000/api/users/62a4ed705f3ddf97f52e7635 HTTP/1.1
Content-Type: application/json

{
    "user": "Otto"
}

### Delete user
DELETE http://localhost:9000/api/users/62a647e6dfa2cf15bdb744bd HTTP/1.1
Content-Type: application/json

{
    "key": "8888"
}

### Make post
POST http://localhost:9000/api/post HTTP/1.1
Content-Type: application/json

{
    "user": "John",
    "postBody": "Sample pos text 2."
}

### Get posts from user
GET http://localhost:9000/api/post/John HTTP/1.1
Content-Type: application/json

### Get posts
GET http://localhost:9000/api/post HTTP/1.1
Content-Type: application/json